name: Terraform Infra Deployment

on:
  push:
    paths:
      - infra/**
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Terraform Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Set Terraform Workspace Name
        run: echo "TF_WORKSPACE=wiz-default" >> $GITHUB_ENV

      - name: Configure Terraform CLI Auth for JFrog Remote Backend
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "solengeu.jfrog.io": {
                "token": "${{ secrets.JFROG_TF_TOKEN }}"
              }
            }
          }
          EOF

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Plan
        run: terraform -chdir=infra plan

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve
